extends Node

var PossibleNames = [
	"Pilgrim’s Progress",
	"Robinson Crusoe",
	"Gulliver’s Travel",
	"Clarissa",
	"Tom Jones",
	"Tristram Shandy",
	"Emma",
	"Frankenstein",
	"Nightmare Abbey",
	"Narrative",
	"Sybil",
	"Jane Eyre",
	"Wuthering Heights",
	"Vanity Fair",
	"David Copperfield",
	"Scarlet Letter",
	"Moby Dick",
	"Wonderland",
	"Moonstone",
	"Little Women",
	"Middlemarch",
	"Huckleberry Finn",
	"Three Men in a Boat",
	"Sign of Four",
	"Dorian Gray",
	"Grub Street",
	"Jude the Obscure",
	"Red Badge of Courage",
	"Dracula",
	"Heart of Darkness",
	"Sister Carrie",
	"Kim",
	"Call of the Wild",
	"Golden Bowl",
	"Hadrian the Seventh",
	"Wind in the Willow",
	"History of Mr Polly",
	"Zuleika Dobson",
	"Good Soldier",
	"Thirty-Nine Steps",
	"Rainbow",
	"Of Human Bondage",
	"Age of Innocence",
	"Ulysses",
	"Babbitt",
	"Passage to India",
	"Gentlemen Prefer Blondes",
	"Mrs Dalloway",
	"Great Gatsby",
	"Lolly Willowes",
	"Sun Also Rises",
	"Maltese Falcon",
	"Lay Dying",
	"Brave New World",
	"Cold Comfort Farm",
	"Nineteen Nineteen",
	"Tropic of Cancer",
	"Scoop",
	"Murphy",
	"Big Sleep",
	"Party Going",
	"Swim-Two-Birds",
	"Grapes of Wrath",
	"Joy in the Morning",
	"All the King’s Men",
	"Under the Volcano",
	"Heat of the Day",
	"Nineteen Eighty-Four",
	"End of the Affair",
	"Catcher in the Rye",
	"Adventures of Augie",
	"Lord of the Flies",
	"Lolita",
	"On the Road",
	"Voss",
	"Mockingbird",
	"Miss Jean Brodie",
	"Catch-22",
	"Golden Notebook",
	"Clockwork Orange",
	"Single Man",
	"Cold Blood",
	"Bell Jar",
	"Portnoy’s Complaint",
	"Mrs Palfrey",
	"Rabbit Redux",
	"Song of Solomon",
	"Bend in the River",
	"Midnight’s Children",
	"Housekeeping",
	"Suicide Note",
	"Beginning of Spring",
	"Breathing Lesson",
	"Amongst Women",
	"Underworld",
	"True History"
]

enum Approach {
	PASSIVE,
	DEFENSIVE,
	OFFENSIVE,
}

enum Type {
	PLACE_OBSERVATION,
	PERSON_OBSERVATION,
	PERSON_RECRUITMENT,
	PERSON_KIDNAPPING,
	PERSON_ASSASINATION,
	TECHNOLOGY_STEALING,
	TECHNOLOGY_DESTROYING,
}

enum Stage {
	NOT_STARTED,
	FINDING_LOCATION,
	PLANNING_OPERATION,
	ABROAD_OPERATION,
	FINISHED,
}

func NewOperation():
	var whichName = randi() % PossibleNames.size()
	var theName = PossibleNames[whichName]
	PossibleNames.remove(whichName)  # to avoid using the same name again
	return {
		"Name": theName,
		"Type": Type.PLACE_OBSERVATION,
		"GoalDescription": "Gather intel on " + WorldData.Targets[0].Name,
		"Level": "Unclassified",  # level displayed in calls
		"Target": 0,  # id from WorldData.Targets, it contains location
		"AnalyticalOfficers": 0,
		"OperationalOfficers": 0,
		"Stage": Stage.NOT_STARTED,
		"AbroadPlan": null,
		"AbroadRateOfProgress": 10,
		"AbroadProgress": 100,
		"WeeksPassed": 0,
		"ExpectedWeeks": 2+3,
		"ExpectedQuality": 20,
		"Started": "-//-",
		"Result": "NOT STARTED",
	}
